# Generated by Django 4.2 on 2023-04-15 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20201230_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='size',
            field=models.CharField(default=2, max_length=10),
            preserve_default=False,
        ),
    ]
