# Generated by Django 4.2 on 2023-04-15 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_cart_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('COD', 'COD')], default=2, max_length=100),
            preserve_default=False,
        ),
    ]
